model = "gpt-5.3-codex"
review_model = "gpt-5.3-codex"
model_provider = "openai"
personality = "pragmatic"

model_reasoning_effort = "high"
model_reasoning_summary = "auto"

approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "cached"

cli_auth_credentials_store = "keyring"
mcp_oauth_credentials_store = "keyring"

project_doc_max_bytes = 65536
project_doc_fallback_filenames = ["AGENT.md", "README.md"]
file_opener = "vscode"

check_for_update_on_startup = true

[sandbox_workspace_write]
writable_roots = []
network_access = true
exclude_tmpdir_env_var = false
exclude_slash_tmp = false

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = false
exclude = []
set = {}
include_only = []
experimental_use_profile = false

[history]
persistence = "save-all"

[tui]
notifications = ["approval-requested", "agent-turn-complete"]
animations = true
show_tooltips = true

[feedback]
enabled = true

[features]
shell_tool = true
apps = true
apps_mcp_gateway = true
unified_exec = true
shell_snapshot = true
apply_patch_freeform = true
personality = true
request_rule = true
collaboration_modes = true
powershell_utf8 = true
child_agents_md = true

[mcp_servers]

[mcp_servers.neon]
url = "https://mcp.neon.tech/mcp"
bearer_token_env_var = "NEON_API_KEY"
startup_timeout_sec = 15.0
tool_timeout_sec = 90.0

[mcp_servers.clerk]
url = "https://mcp.clerk.com/mcp"
bearer_token_env_var = "AUTH_CLERK_SECRET_KEY"
startup_timeout_sec = 15.0
tool_timeout_sec = 90.0

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"
startup_timeout_sec = 15.0
tool_timeout_sec = 90.0

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
startup_timeout_sec = 15.0
tool_timeout_sec = 120.0

[mcp_servers."io.github.github/github-mcp-server"]
url = "https://api.githubcopilot.com/mcp/"
startup_timeout_sec = 15.0
tool_timeout_sec = 90.0

[apps]

[apps.github]
enabled = true

[apps.vercel]
enabled = true

[apps.notion]
enabled = true

[projects]
[projects."d:\\CtrlPlus"]
trust_level = "trusted"

[otel]
log_user_prompt = false
environment = "dev"
exporter = "none"
trace_exporter = "none"
